        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_TOKEN }}
          RELEASE_API_URL: ${{ secrets.RELEASE_API_URL }}
        run: |
          # Fetch Asset ID dynamically using hidden API base URL
          ASSET_ID=$(curl -sH "Authorization: Bearer $GITHUB_TOKEN" \
            "$RELEASE_API_URL/tags/g7" \
            | jq '.assets[] | select(.name=="jrtio.tar") | .id')

          # Download using hidden API base URL
          curl -L \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/octet-stream" \
            -o jrtio.tar \
            "$RELEASE_API_URL/assets/$ASSET_ID"
            tar -xf jrtio.tar
            ls
