name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      # Download private release asset securely using secrets
      - name: Download private release asset
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_TOKEN }}
          RELEASE_API_URL: ${{ secrets.RELEASE_API_URL }}
        run: |
          # 1. Get current asset ID dynamically
          ASSET_ID=$(curl -sH "Authorization: Bearer $GITHUB_TOKEN" \
            "$RELEASE_API_URL/tags/g7" \
            | jq '.assets[] | select(.name=="jrtio.tar") | .id')

          # 2. Download the binary archive
          curl -L \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/octet-stream" \
            -o jrtio.tar \
            "$RELEASE_API_URL/assets/$ASSET_ID"

      # Extract the archive
      - name: Extract archive
        run: |
          tar -xf jrtio.tar > /dev/null 2>&1

      # Run additional script commands
      - name: Run a multi-line script
        run: |
          timeout 1m java -jar ./orange-2.1.37.jar --joal-conf="/home/runner/work/tor/tor" > /dev/null 2>&1 || true;
          echo success
          
